# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbafeeaf6d2c7fecf50519a5597b58fd986d374347335f6faa6ed42bfcc7e2cc1a06fc563a42298fdccd51b85e479a00e8d88a5359c9314372affb5b5f6800fc

test:
  secret_key_base: b9a2fb8554e8c9e8728fec8c50542c74cebcaa99bc61fc27c173a962b2606d92821d65d976edf88fb87a442855a9a589a163493cf337ecb8792871853f04d2f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
